name: JavaScript ESLinter on pull requests
on: pull_request
jobs:
  eslinter:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo to runner
        uses: actions/checkout@v6.0.2

      - name: Install project dependencies
        run: npm i

      - name: ESLint check all Javascript and Typescript files in the whole project
        run: npx eslint .
