name: JavaScript ESLinter on pull requests
on: pull_request
jobs:
  eslinter:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo to runner
        uses: actions/checkout@v6.0.2

      - name: Install project depencies
        run: npm i

      - name: Run ESLint
        run: npx eslint *.js
